### ISSUE TITLE
h5文件如何生成？

### ISSUE THREAD

**Issue by blingsr** [hellloxiaotian/PSDNet#2]
你好！请问生成h5文件所涉及到DIV2K文件里面包含哪些子文件？

能否给出具体的说明？

比如：  .. /DIV2K/XXX/XXX

**Comment by hellloxiaotian** [comment]
您好! 可以根一下读取数据集，这样能更直观地知道生成h5文件中包括DIV2K的哪些图像。
祝好
田春伟 副教授
西北工业大学
