### ISSUE TITLE
sample

### ISSUE THREAD

**Issue by thestars-maker** [hellloxiaotian/PSDNet#4]

**Comment by thestars-maker** [comment]
RuntimeError: Error(s) in loading state_dict for Net:
	Unexpected key(s) in state_dict: "upsample.up.body.0.weight", "upsample.up.body.0.bias", "upsample.up.body.2.weight", "upsample.up.body.2.bias".

**Comment by aoyang-hd** [comment]
> RuntimeError: Error(s) in loading state_dict for Net: Unexpected key(s) in state_dict: "upsample.up.body.0.weight", "upsample.up.body.0.bias", "upsample.up.body.2.weight", "upsample.up.body.2.bias".

me too ,

**Comment by hellloxiaotian** [comment]
The pretrained model you load may not match with the up-sampling  factor you set.
We have updated the relevant files and annotation. Thank you for your attention.
